config/routes.rb
#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require 'sidekiq/web'
require 'sidetiq/web'

Diaspora::Application.routes.draw do

  mount RailsAdmin::Engine => '/administrator', as: 'rails_admin'
  resources :report
  #resources :report, :except => [:edit, :new]

  if Rails.env.production?
    mount RailsAdmin::Engine => '/admin_panel', :as => 'rails_admin'
  end

  constraints ->(req) { req.env["warden"].authenticate?(scope: :user) &&
                        req.env['warden'].user.admin? } do
    mount Sidekiq::Web => '/sidekiq', :as => 'sidekiq'
  end

  get "/atom.xml" => redirect('http://blog.diasporafoundation.org/feed/atom') #too many stupid redirects :()

  get 'oembed' => 'posts#oembed', :as => 'oembed'
  # Posting and Reading
  resources :reshares

  resources :status_messages, :only => [:new, :create]

  resources :posts do
    member do
      get :next
      get :previous
      get :interactions
    end

    resources :poll_participations, :only => [:create]

    resources :likes, :only => [:create, :destroy, :index ]
    resource :participation, :only => [:create, :destroy]
    resources :comments, :only => [:new, :create, :destroy, :index]
  end



  get 'p/:id' => 'posts#show', :as => 'short_post'
  get 'posts/:id/iframe' => 'posts#iframe', :as => 'iframe'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end

  # Streams
  get "participate" => "streams#activity" # legacy
  get "explore" => "streams#multi"        # legacy

  get "activity" => "streams#activity", :as => "activity_stream"
  get "stream" => "streams#multi", :as => "stream"
  get "public" => "streams#public", :as => "public_stream"
  get "followed_tags" => "streams#followed_tags", :as => "followed_tags_stream"
  get "mentions" => "streams#mentioned", :as => "mentioned_stream"
  get "liked" => "streams#liked", :as => "liked_stream"
  get "commented" => "streams#commented", :as => "commented_stream"
  get "aspects" => "streams#aspects", :as => "aspects_stream"

  resources :aspects do
    put :toggle_contact_visibility
    put :toggle_chat_privilege
    collection do
      put "order" => :update_order
    end
  end

  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, :except => [:index, :show] do
    put :make_profile_photo
  end

	#Search
	get 'search' => "search#search"

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    collection do
      get :read_all
    end
  end


  resources :tags, :only => [:index]

  resources "tag_followings", only: %i(create destroy index) do
    collection do
      get :manage
    end
  end

  get 'tags/:name' => 'tags#show', :as => 'tag'

  resources :apps, :only => [:show]

  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :getting_started_completed
    post :export_profile
    get :download_profile
    post :export_photos
    get :download_photos
  end

  controller :users do
    get 'public/:username'          => :public,           :as => 'users_public'
    get 'getting_started'           => :getting_started,  :as => 'getting_started'
    get 'privacy'                   => :privacy_settings, :as => 'privacy_settings'
    get 'getting_started_completed' => :getting_started_completed
    get 'confirm_email/:token'      => :confirm_email,    :as => 'confirm_email'
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  get 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :sessions      => "sessions"}

  #legacy routes to support old invite routes
  get 'users/invitation/accept' => 'invitations#edit'
  get 'invitations/email' => 'invitations#email', :as => 'invite_email'
  get 'users/invitations' => 'invitations#new', :as => 'new_user_invitation'
  post 'users/invitations' => 'invitations#create', :as => 'user_invitation'

  get 'login' => redirect('/users/sign_in')

  # Admin backend routes

  scope 'admins', :controller => :admins do
    match :user_search, via: [:get, :post]
    get   :admin_inviter
    get   :weekly_user_stats
    get   :correlations
    get   :stats, :as => 'pod_stats'
    get   "add_invites/:invite_code_id" => 'admins#add_invites', :as => 'add_invites'
  end

  namespace :admin do
    post 'users/:id/close_account' => 'users#close_account', :as => 'close_account'
    post 'users/:id/lock_account' => 'users#lock_account', :as => 'lock_account'
    post 'users/:id/unlock_account' => 'users#unlock_account', :as => 'unlock_account'
  end

  resource :profile, :only => [:edit, :update]
  resources :profiles, :only => [:show]


  resources :contacts,           :except => [:update, :create] do
  end
  resources :aspect_memberships, :only  => [:destroy, :create]
  resources :share_visibilities,  :only => [:update]
  resources :blocks, :only => [:create, :destroy]

  get 'i/:id' => 'invitation_codes#show', :as => 'invite_code'

  get 'people/refresh_search' => "people#refresh_search"
  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get :contacts
    get "aspect_membership_button" => :aspect_membership_dropdown, :as => "aspect_membership_button"
    get :stream
    get :hovercard

    member do
      get :last_post
    end

    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
      get :tag_index
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile', :constraints => { :username => /[^\/]+/ }
  get '/u/:username/profile_photo' => 'users#user_photo', :constraints => { :username => /[^\/]+/ }


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    post 'receive/public'       => :receive_public
    get 'hub'                   => :hub
  end



  # External

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end

  scope 'api/v0', :controller => :apis do
    get :me
  end

  namespace :api do
    namespace :v0 do
      get "/users/:username" => 'users#show', :as => 'user'
      get "/tags/:name" => 'tags#show', :as => 'tag'
    end
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
    end
  end

  get 'community_spotlight' => "contacts#spotlight", :as => 'community_spotlight'
  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'

  # Help
  get 'help' => 'help#faq', :as => 'help'
  get 'help/:topic' => 'help#faq'

  #Protocol Url
  get 'protocol' => redirect("http://wiki.diasporafoundation.org/Federation_Protocol_Overview")

  #Statistics
  get :statistics, controller: :statistics

  # Terms
  if AppConfig.settings.terms.enable?
    get 'terms' => 'terms#index'
  end

  # Startpage
  root :to => 'home#show'

  resources :detailbooks
end

app/views/shared/_donatepod.html.haml
- if AppConfig.settings.paypal_donations.enable?
  PayPal:
  %form{action: "https://www.paypal.com/cgi-bin/webscr", method: "post", target: "_blank"}
    %input{name: "cmd", type: "hidden", value: "_s-xclick"}
    - if AppConfig.settings.paypal_donations.paypal_hosted_button_id.present?
      %input{name: "hosted_button_id", type: "hidden", value: AppConfig.settings.paypal_donations.paypal_hosted_button_id}
    -if AppConfig.settings.paypal_donations.paypal_unhosted_button_encrypted.present?
      %input{name: "encrypted", type: "hidden", value: AppConfig.settings.paypal_donations.paypal_unhosted_button_encrypted}
    %input{name: "currency_code", type: "hidden", value: AppConfig.settings.paypal_donations.currency}
    %input{name: "submit", type: "submit", value: t("aspects.index.donate"), class: "btn btn-default"}

- if AppConfig.bitcoin_donation_address
  Bitcoin:
  %input{type: "text", id: "bitcoin_address", value: AppConfig.bitcoin_donation_address, readonly: true}

app/views/shared/_invitations.haml
= t('.share_this')
= invite_link(current_user.invitation_code)
.btn-link{ 'data-toggle' => 'modal', 'data-target' => '#invitationsModal'}
  = t('.by_email')

= render 'shared/modal',
    :path => new_user_invitation_path, 
    :id => 'invitationsModal',
    :title => t('invitations.new.invite_someone_to_join')

app/views/shared/_links.haml
%li= link_to 'diasporafoundation.org', "https://diasporafoundation.org"
%li= link_to 'wiki', "https://wiki.diasporafoundation.org"
%li= link_to t('layouts.application.whats_new'), changelog_url
%li= link_to t('layouts.header.code') + " " + pod_version, "#{source_url}", {:title => t('layouts.application.source_package')}
%li= link_to t("layouts.application.statistics_link"), statistics_path
%li= link_to(t('layouts.application.toggle'), toggle_mobile_path)
- if AppConfig.settings.terms.enable?
    %li= link_to(t('_terms'), terms_path)

app/views/shared/_modal.haml
.modal.hide.fade{ :id => id, 
                  :tabindex => '-1', 
                  :role => 'dialog', 
                  'aria-labelledby' => "#{id}Label", 
                  'aria-hidden' => 'true', 
                  'data-remote' => path}
  .modal-header
    %button.close{:type => 'button', 'data-dismiss' => 'modal', 'aria-hidden' => 'true' }
      &times;
    %h3{ :id => "#{id}Label"}
      = title
  .modal-body

app/views/shared/_public_explain.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.span-12.last
  .modal_title_bar
    %h4=t('.title')
  %p
    =t('.outside')
    %br
    %br
    = link_to t('.atom_feed'), "#{current_user.public_url}.atom"
    %br
    - if current_user.services
      - for service in current_user.services
        = t('.logged_in', :service => service.provider)
        %br

    = link_to t('.manage'), services_path

    %br
    %br
    = link_to t('ok'), '#', :class => "button", :onClick => '$.facebox.close();'

app/views/shared/_right_sections.html.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


- if AppConfig.settings.invitations.open?
  .section
    .title
      %h5.title-header
        %i.entypo.plus
        = t('shared.invitations.invite_your_friends')
    .content
      = render "shared/invitations"

.section
  .title
    %h5.title-header
      %i.entypo.users
      = t('aspects.index.new_here.title')
  .content
    != t('aspects.index.new_here.follow', link: link_to("#"+t('shared.publisher.new_user_prefill.newhere'), tag_path(name: t('shared.publisher.new_user_prefill.newhere'))))
    %br
    = link_to(t('aspects.index.new_here.learn_more'), "http://wiki.diasporafoundation.org/Welcoming_Committee")

.section
  .title
    %h5.title-header
      %i.entypo.circled-help
      = t('aspects.index.help.need_help')
  .content
    %p
      = t('aspects.index.help.here_to_help')
    %p
      = t('aspects.index.help.do_you')
    %ul
      %li
        != t('aspects.index.help.have_a_question', :link => link_to("#"+t('aspects.index.help.tag_question'), tag_path(:name => t('aspects.index.help.tag_question'))))
      %li
        != t('aspects.index.help.find_a_bug', :link => link_to("#"+t('aspects.index.help.tag_bug'), tag_path(:name => t('aspects.index.help.tag_bug'))))
      %li
        != t('aspects.index.help.feature_suggestion', :link => link_to("#"+t('aspects.index.help.tag_feature'), tag_path(:name => t('aspects.index.help.tag_feature'))))
    %p
      != t('aspects.index.help.tutorials_and_wiki',
           :faq => link_to(t('_help'), help_path),
           :tutorial => link_to(t('aspects.index.help.tutorial_link_text'), "https://diasporafoundation.org/tutorials", :target => '_blank'),
           :wiki => link_to('Wiki','http://wiki.diasporafoundation.org', :target => '_blank'), :target => '_blank')

- unless AppConfig.configured_services.blank? || all_services_connected?
  .section
    .title
      %h5.title-header
        %i.entypo.cog
        = t('aspects.index.services.heading')
    .content
      %div
        = t('aspects.index.services.content')

      #right_service_icons
        - AppConfig.configured_services.each do |service|
          - if AppConfig.show_service?(service, current_user)
            - unless current_user.services.any?{|x| x.provider == service}
              = link_to(content_tag(:div, nil, :class => "social_media_logos-#{service.to_s.downcase}-24x24", :title => service.to_s.titleize), "/auth/#{service}")

.section
  .title
    %h5.title-header
      %i.entypo.bookmark
      = t('bookmarklet.heading')
  .content
    != t('bookmarklet.explanation', :link => link_to(t('bookmarklet.post_something'), bookmarklet_url))

- if AppConfig.settings.paypal_donations.enable? || AppConfig.bitcoin_donation_address
  .section
    .title
      %h5.title-header
        %i.entypo.heart
        = t('aspects.index.donate')
    .content
      %p
        = t('aspects.index.keep_pod_running', :pod => AppConfig.pod_uri.host)
      = render 'shared/donatepod'

- if AppConfig.admins.podmin_email.present?
  .section
    .title
      %h5.title-header
        %i.entypo.mail
        = t('aspects.index.help.any_problem')
    .content
      %p
        = t('aspects.index.help.contact_podmin')
      %p
        = link_to t('aspects.index.help.mail_podmin'), "mailto:#{AppConfig.admins.podmin_email}", :class => "button"

.section
  .title
  .content
    %ul
      = render "shared/links"

app/views/shared/_settings_nav.haml
%ul.nav.nav-tabs#settings_nav
  %li{class: current_page?(edit_profile_path) && 'active'}= link_to t('profile'), edit_profile_path
  %li{class: current_page?(edit_user_path) && 'active'}= link_to t('account'), edit_user_path
  %li{class: current_page?(privacy_settings_path) && 'active'}= link_to t('privacy'), privacy_settings_path
  %li{class: current_page?(services_path) && 'active'}= link_to t('_services'), services_path
  %li{class: current_page?(detailbooks_path) && 'active'}= link_to t('_detailbooks'), detailbooks_path

app/views/shared/_stream.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

= render :partial => 'shared/stream_element',
         :collection => posts,
         :as => :post

app/views/shared/_stream_element.mobile.haml
-#   Copyright (c) 2010-2011, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.

.stream_element{data: {guid: post.id}}
  - if post.respond_to?(:nsfw) && post.nsfw
    .shield_wrapper
      .shield
        %strong #NSFW 
        | 
        = link_to t("javascripts.stream.show_nsfw_post"), "#"
  
  - if post.is_a?(Reshare)
    = render "reshares/reshare", reshare: post, post: post.absolute_root

  = render "shared/photo_area", post: post

  .content
    = render "shared/post_info", post: post

    - if post.is_a?(StatusMessage)
      = render "status_messages/status_message", post: post, photos: post.photos

  .bottom_bar
    .floater
      = mobile_reshare_icon(post)
      = mobile_comment_icon(post)
      = mobile_like_icon(post)

    != reactions_link(post)

    - if defined?(expanded_info) && expanded_info
      = render partial: "shared/post_stats", locals: {post: @post}